// actions.ts
export const GO_TO_NEXT_QUESTION = 'GO_TO_NEXT_QUESTION';
export const GO_TO_PREVIOUS_QUESTION = 'GO_TO_PREVIOUS_QUESTION';
export const FINISH_QUIZ = 'FINISH_QUIZ';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const SAVE_QUIZ_RESULT = 'SAVE_QUIZ_RESULT';
export const FETCH_QUIZ_RESULT_BY_ID = 'FETCH_QUIZ_RESULT_BY_ID';
export const FETCH_QUIZ_HISTORY = 'FETCH_QUIZ_HISTORY';
export const SAVE_ANSWERED_QUESTIONS = 'SAVE_ANSWERED_QUESTIONS';
export const FETCH_COMPREHENSIVE_QUIZ_RESULT = 'FETCH_COMPREHENSIVE_QUIZ_RESULT';
export const FETCH_USED_QUESTION_IDS = 'FETCH_USED_QUESTION_IDS';
